### ISSUE TITLE
Issue with Mediawiki 1.42.3

### ISSUE THREAD

**Issue by JLTRY** [chdh/AuthJoomla#1]
When used with mediawiki 1.42.3 I have got an error
 /Wiki?title=Wiki InvalidArgumentException: Invalid key type: boolean

Backtrace:

from /home/jltryoen/www/MediaWiki/includes/libs/MWCryptHash.php(100)
#0 /home/jltryoen/www/MediaWiki/includes/session/SessionProvider.php(705): MWCryptHash::hmac(string, boolean, boolean)
#1 /home/jltryoen/www/MediaWiki/extensions/AuthJoomla2023/src/AuthJoomlaSessionProvider.php(40): MediaWiki\Session\SessionProvider->hashToSessionId(string)
#2 /home/jltryoen/www/MediaWiki/includes/session/SessionManager.php(539): MediaWiki\Extension\AuthJoomla2023\AuthJoomlaSessionProvider->provideSessionInfo(MediaWiki\Request\WebRequest)
#3 /home/jltryoen/www/MediaWiki/includes/session/SessionManager.php(245): MediaWiki\Session\SessionManager->getSessionInfoForRequest(MediaWiki\Request\WebRequest)
#4 /home/jltryoen/www/MediaWiki/includes/Request/WebRequest.php(870): MediaWiki\Session\SessionManager->getSessionForRequest(MediaWiki\Request\WebRequest)
#5 /home/jltryoen/www/MediaWiki/includes/session/SessionManager.php(166): MediaWiki\Request\WebRequest->getSession()
#6 /home/jltryoen/www/MediaWiki/includes/Setup.php(487): MediaWiki\Session\SessionManager::getGlobalSession()
#7 /home/jltryoen/www/MediaWiki/includes/WebStart.php(85): require_once(string)
#8 /home/jltryoen/www/MediaWiki/index.php(50): require(string)
#9 {main}

**Comment by chdh** [comment]
I just upgraded to MediaWiki 1.42.3 and I cannot reproduce this error.

The error position is at line 100 in MediaWiki/includes/libs/MWCryptHash.php. The `$key` argument of `hmac()` is of type `boolean`instead of `string`.

This key comes from line 705 in MediaWiki/includes/session/SessionProvider.php:
`$key ?: $this->getConfig()->get( MainConfigNames::SecretKey )`
`MainConfigNames::SecretKey` is `'SecretKey'`.

So I assume that the `SecretKey` (`$wgSecretKey`) parameter is not set in your configuration (LocalSettings.php) or there is something wrong with your configuration.

Does your wiki run without the AuthJoomla extension?

**Comment by JLTRY** [comment]
you are right the variable $wgSecretKey was missing from my LocalSettings.php
Thks
